Repository PitchapaSaelim/Have-A-Night-Day, pull requests merged in 2020-10, with the labels that each got.

#23 Improve the registration page
  Have_A_Night_Day/urls.py
  sleep_time_management/templates/sleep_time_management/home.html
  user/static/user/login.css
  user/templates/login.html
  user/views.py
Labels: enhancement

#25 Calculator3
  Have_A_Night_Day/urls.py
  sleep_time_management/templates/sleep_time_management/calculator2.html
  sleep_time_management/templates/sleep_time_management/calculator3.html
  sleep_time_management/templates/sleep_time_management/editprofile.html
  sleep_time_management/templates/sleep_time_management/mainprofile.html
  sleep_time_management/urls.py
  sleep_time_management/views.py
Labels: enhancement

#30 Improve CSS and HTML on registration page.
  user/static/user/register.css
  user/templates/navbar.html
  user/templates/register.html
Labels: enhancement

#31 Improve HTML on registration page.
  user/templates/register.html
Labels: enhancement

#32 Make a web application that can collect data from users’ profiles.
  user/form.py
  user/templates/register.html
  user/views.py
Labels: enhancement

#44 Improve a calculator page
  sleep_time_management/templates/sleep_time_management/home.html
  user/static/user/home.css
  user/static/user/navbar.css
Labels: enhancement, frontend

#45 Creating tests.
  sleep_time_management/migrations/0002_auto_20201028_2211.py
  user/migrations/0001_initial.py
  user/models.py
  user/tests.py
Labels: testing
